// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: smartivrphonegateway.proto

#include "smartivrphonegateway.pb.h"
#include "smartivrphonegateway.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace smartivrphonegateway {

static const char* SmartIVRPhonegateway_method_names[] = {
  "/smartivrphonegateway.SmartIVRPhonegateway/CallToBot",
};

std::unique_ptr< SmartIVRPhonegateway::Stub> SmartIVRPhonegateway::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SmartIVRPhonegateway::Stub> stub(new SmartIVRPhonegateway::Stub(channel, options));
  return stub;
}

SmartIVRPhonegateway::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CallToBot_(SmartIVRPhonegateway_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::smartivrphonegateway::SmartIVRRequest, ::smartivrphonegateway::SmartIVRResponse>* SmartIVRPhonegateway::Stub::CallToBotRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::smartivrphonegateway::SmartIVRRequest, ::smartivrphonegateway::SmartIVRResponse>::Create(channel_.get(), rpcmethod_CallToBot_, context);
}

void SmartIVRPhonegateway::Stub::async::CallToBot(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::smartivrphonegateway::SmartIVRRequest,::smartivrphonegateway::SmartIVRResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::smartivrphonegateway::SmartIVRRequest,::smartivrphonegateway::SmartIVRResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_CallToBot_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::smartivrphonegateway::SmartIVRRequest, ::smartivrphonegateway::SmartIVRResponse>* SmartIVRPhonegateway::Stub::AsyncCallToBotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::smartivrphonegateway::SmartIVRRequest, ::smartivrphonegateway::SmartIVRResponse>::Create(channel_.get(), cq, rpcmethod_CallToBot_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::smartivrphonegateway::SmartIVRRequest, ::smartivrphonegateway::SmartIVRResponse>* SmartIVRPhonegateway::Stub::PrepareAsyncCallToBotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::smartivrphonegateway::SmartIVRRequest, ::smartivrphonegateway::SmartIVRResponse>::Create(channel_.get(), cq, rpcmethod_CallToBot_, context, false, nullptr);
}

SmartIVRPhonegateway::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SmartIVRPhonegateway_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< SmartIVRPhonegateway::Service, ::smartivrphonegateway::SmartIVRRequest, ::smartivrphonegateway::SmartIVRResponse>(
          [](SmartIVRPhonegateway::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::smartivrphonegateway::SmartIVRResponse,
             ::smartivrphonegateway::SmartIVRRequest>* stream) {
               return service->CallToBot(ctx, stream);
             }, this)));
}

SmartIVRPhonegateway::Service::~Service() {
}

::grpc::Status SmartIVRPhonegateway::Service::CallToBot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::smartivrphonegateway::SmartIVRResponse, ::smartivrphonegateway::SmartIVRRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace smartivrphonegateway

