// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartivrphonegateway.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_smartivrphonegateway_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_smartivrphonegateway_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_smartivrphonegateway_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_smartivrphonegateway_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_smartivrphonegateway_2eproto;
namespace smartivrphonegateway {
class Config;
struct ConfigDefaultTypeInternal;
extern ConfigDefaultTypeInternal _Config_default_instance_;
class SmartIVRRequest;
struct SmartIVRRequestDefaultTypeInternal;
extern SmartIVRRequestDefaultTypeInternal _SmartIVRRequest_default_instance_;
class SmartIVRResponse;
struct SmartIVRResponseDefaultTypeInternal;
extern SmartIVRResponseDefaultTypeInternal _SmartIVRResponse_default_instance_;
class Status;
struct StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
}  // namespace smartivrphonegateway
PROTOBUF_NAMESPACE_OPEN
template <>
::smartivrphonegateway::Config* Arena::CreateMaybeMessage<::smartivrphonegateway::Config>(Arena*);
template <>
::smartivrphonegateway::SmartIVRRequest* Arena::CreateMaybeMessage<::smartivrphonegateway::SmartIVRRequest>(Arena*);
template <>
::smartivrphonegateway::SmartIVRResponse* Arena::CreateMaybeMessage<::smartivrphonegateway::SmartIVRResponse>(Arena*);
template <>
::smartivrphonegateway::Status* Arena::CreateMaybeMessage<::smartivrphonegateway::Status>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace smartivrphonegateway {
enum SmartIVRResponseType : int {
  RECOGNIZE = 0,
  RESULT_ASR = 1,
  RESULT_TTS = 2,
  CALL_WAIT = 3,
  CALL_FORWARD = 4,
  CALL_END = 5,
  SmartIVRResponseType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SmartIVRResponseType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SmartIVRResponseType_IsValid(int value);
constexpr SmartIVRResponseType SmartIVRResponseType_MIN = static_cast<SmartIVRResponseType>(0);
constexpr SmartIVRResponseType SmartIVRResponseType_MAX = static_cast<SmartIVRResponseType>(5);
constexpr int SmartIVRResponseType_ARRAYSIZE = 5 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
SmartIVRResponseType_descriptor();
template <typename T>
const std::string& SmartIVRResponseType_Name(T value) {
  static_assert(std::is_same<T, SmartIVRResponseType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SmartIVRResponseType_Name().");
  return SmartIVRResponseType_Name(static_cast<SmartIVRResponseType>(value));
}
template <>
inline const std::string& SmartIVRResponseType_Name(SmartIVRResponseType value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<SmartIVRResponseType_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool SmartIVRResponseType_Parse(absl::string_view name, SmartIVRResponseType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SmartIVRResponseType>(
      SmartIVRResponseType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class SmartIVRRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:smartivrphonegateway.SmartIVRRequest) */ {
 public:
  inline SmartIVRRequest() : SmartIVRRequest(nullptr) {}
  ~SmartIVRRequest() override;
  explicit PROTOBUF_CONSTEXPR SmartIVRRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SmartIVRRequest(const SmartIVRRequest& from);
  SmartIVRRequest(SmartIVRRequest&& from) noexcept
    : SmartIVRRequest() {
    *this = ::std::move(from);
  }

  inline SmartIVRRequest& operator=(const SmartIVRRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SmartIVRRequest& operator=(SmartIVRRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SmartIVRRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SmartIVRRequest* internal_default_instance() {
    return reinterpret_cast<const SmartIVRRequest*>(
               &_SmartIVRRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SmartIVRRequest& a, SmartIVRRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SmartIVRRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SmartIVRRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SmartIVRRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SmartIVRRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SmartIVRRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SmartIVRRequest& from) {
    SmartIVRRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SmartIVRRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "smartivrphonegateway.SmartIVRRequest";
  }
  protected:
  explicit SmartIVRRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyPressFieldNumber = 2,
    kAudioContentFieldNumber = 4,
    kConfigFieldNumber = 3,
    kIsPlayingFieldNumber = 1,
  };
  // string key_press = 2;
  void clear_key_press() ;
  const std::string& key_press() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_key_press(Arg_&& arg, Args_... args);
  std::string* mutable_key_press();
  PROTOBUF_NODISCARD std::string* release_key_press();
  void set_allocated_key_press(std::string* ptr);

  private:
  const std::string& _internal_key_press() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key_press(
      const std::string& value);
  std::string* _internal_mutable_key_press();

  public:
  // bytes audio_content = 4;
  void clear_audio_content() ;
  const std::string& audio_content() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_audio_content(Arg_&& arg, Args_... args);
  std::string* mutable_audio_content();
  PROTOBUF_NODISCARD std::string* release_audio_content();
  void set_allocated_audio_content(std::string* ptr);

  private:
  const std::string& _internal_audio_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_audio_content(
      const std::string& value);
  std::string* _internal_mutable_audio_content();

  public:
  // .smartivrphonegateway.Config config = 3;
  bool has_config() const;
  private:
  bool _internal_has_config() const;

  public:
  void clear_config() ;
  const ::smartivrphonegateway::Config& config() const;
  PROTOBUF_NODISCARD ::smartivrphonegateway::Config* release_config();
  ::smartivrphonegateway::Config* mutable_config();
  void set_allocated_config(::smartivrphonegateway::Config* config);
  private:
  const ::smartivrphonegateway::Config& _internal_config() const;
  ::smartivrphonegateway::Config* _internal_mutable_config();
  public:
  void unsafe_arena_set_allocated_config(
      ::smartivrphonegateway::Config* config);
  ::smartivrphonegateway::Config* unsafe_arena_release_config();
  // bool is_playing = 1;
  void clear_is_playing() ;
  bool is_playing() const;
  void set_is_playing(bool value);

  private:
  bool _internal_is_playing() const;
  void _internal_set_is_playing(bool value);

  public:
  // @@protoc_insertion_point(class_scope:smartivrphonegateway.SmartIVRRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_press_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr audio_content_;
    ::smartivrphonegateway::Config* config_;
    bool is_playing_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_smartivrphonegateway_2eproto;
};// -------------------------------------------------------------------

class SmartIVRResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:smartivrphonegateway.SmartIVRResponse) */ {
 public:
  inline SmartIVRResponse() : SmartIVRResponse(nullptr) {}
  ~SmartIVRResponse() override;
  explicit PROTOBUF_CONSTEXPR SmartIVRResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SmartIVRResponse(const SmartIVRResponse& from);
  SmartIVRResponse(SmartIVRResponse&& from) noexcept
    : SmartIVRResponse() {
    *this = ::std::move(from);
  }

  inline SmartIVRResponse& operator=(const SmartIVRResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SmartIVRResponse& operator=(SmartIVRResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SmartIVRResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SmartIVRResponse* internal_default_instance() {
    return reinterpret_cast<const SmartIVRResponse*>(
               &_SmartIVRResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SmartIVRResponse& a, SmartIVRResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SmartIVRResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SmartIVRResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SmartIVRResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SmartIVRResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SmartIVRResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SmartIVRResponse& from) {
    SmartIVRResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SmartIVRResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "smartivrphonegateway.SmartIVRResponse";
  }
  protected:
  explicit SmartIVRResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextAsrFieldNumber = 2,
    kTextBotFieldNumber = 3,
    kForwardSipJsonFieldNumber = 4,
    kAudioContentFieldNumber = 6,
    kStatusFieldNumber = 5,
    kTypeFieldNumber = 1,
  };
  // string text_asr = 2;
  void clear_text_asr() ;
  const std::string& text_asr() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text_asr(Arg_&& arg, Args_... args);
  std::string* mutable_text_asr();
  PROTOBUF_NODISCARD std::string* release_text_asr();
  void set_allocated_text_asr(std::string* ptr);

  private:
  const std::string& _internal_text_asr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text_asr(
      const std::string& value);
  std::string* _internal_mutable_text_asr();

  public:
  // string text_bot = 3;
  void clear_text_bot() ;
  const std::string& text_bot() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text_bot(Arg_&& arg, Args_... args);
  std::string* mutable_text_bot();
  PROTOBUF_NODISCARD std::string* release_text_bot();
  void set_allocated_text_bot(std::string* ptr);

  private:
  const std::string& _internal_text_bot() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text_bot(
      const std::string& value);
  std::string* _internal_mutable_text_bot();

  public:
  // string forward_sip_json = 4;
  void clear_forward_sip_json() ;
  const std::string& forward_sip_json() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_forward_sip_json(Arg_&& arg, Args_... args);
  std::string* mutable_forward_sip_json();
  PROTOBUF_NODISCARD std::string* release_forward_sip_json();
  void set_allocated_forward_sip_json(std::string* ptr);

  private:
  const std::string& _internal_forward_sip_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_forward_sip_json(
      const std::string& value);
  std::string* _internal_mutable_forward_sip_json();

  public:
  // bytes audio_content = 6;
  void clear_audio_content() ;
  const std::string& audio_content() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_audio_content(Arg_&& arg, Args_... args);
  std::string* mutable_audio_content();
  PROTOBUF_NODISCARD std::string* release_audio_content();
  void set_allocated_audio_content(std::string* ptr);

  private:
  const std::string& _internal_audio_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_audio_content(
      const std::string& value);
  std::string* _internal_mutable_audio_content();

  public:
  // .smartivrphonegateway.Status status = 5;
  bool has_status() const;
  private:
  bool _internal_has_status() const;

  public:
  void clear_status() ;
  const ::smartivrphonegateway::Status& status() const;
  PROTOBUF_NODISCARD ::smartivrphonegateway::Status* release_status();
  ::smartivrphonegateway::Status* mutable_status();
  void set_allocated_status(::smartivrphonegateway::Status* status);
  private:
  const ::smartivrphonegateway::Status& _internal_status() const;
  ::smartivrphonegateway::Status* _internal_mutable_status();
  public:
  void unsafe_arena_set_allocated_status(
      ::smartivrphonegateway::Status* status);
  ::smartivrphonegateway::Status* unsafe_arena_release_status();
  // .smartivrphonegateway.SmartIVRResponseType type = 1;
  void clear_type() ;
  ::smartivrphonegateway::SmartIVRResponseType type() const;
  void set_type(::smartivrphonegateway::SmartIVRResponseType value);

  private:
  ::smartivrphonegateway::SmartIVRResponseType _internal_type() const;
  void _internal_set_type(::smartivrphonegateway::SmartIVRResponseType value);

  public:
  // @@protoc_insertion_point(class_scope:smartivrphonegateway.SmartIVRResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_asr_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_bot_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr forward_sip_json_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr audio_content_;
    ::smartivrphonegateway::Status* status_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_smartivrphonegateway_2eproto;
};// -------------------------------------------------------------------

class Config final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:smartivrphonegateway.Config) */ {
 public:
  inline Config() : Config(nullptr) {}
  ~Config() override;
  explicit PROTOBUF_CONSTEXPR Config(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Config(const Config& from);
  Config(Config&& from) noexcept
    : Config() {
    *this = ::std::move(from);
  }

  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }
  inline Config& operator=(Config&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Config& default_instance() {
    return *internal_default_instance();
  }
  static inline const Config* internal_default_instance() {
    return reinterpret_cast<const Config*>(
               &_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Config& a, Config& b) {
    a.Swap(&b);
  }
  inline void Swap(Config* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Config* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Config* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Config>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Config& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Config& from) {
    Config::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Config* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "smartivrphonegateway.Config";
  }
  protected:
  explicit Config(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConversationIdFieldNumber = 1,
  };
  // string conversation_id = 1;
  void clear_conversation_id() ;
  const std::string& conversation_id() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_conversation_id(Arg_&& arg, Args_... args);
  std::string* mutable_conversation_id();
  PROTOBUF_NODISCARD std::string* release_conversation_id();
  void set_allocated_conversation_id(std::string* ptr);

  private:
  const std::string& _internal_conversation_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_conversation_id(
      const std::string& value);
  std::string* _internal_mutable_conversation_id();

  public:
  // @@protoc_insertion_point(class_scope:smartivrphonegateway.Config)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr conversation_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_smartivrphonegateway_2eproto;
};// -------------------------------------------------------------------

class Status final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:smartivrphonegateway.Status) */ {
 public:
  inline Status() : Status(nullptr) {}
  ~Status() override;
  explicit PROTOBUF_CONSTEXPR Status(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Status(const Status& from);
  Status(Status&& from) noexcept
    : Status() {
    *this = ::std::move(from);
  }

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Status& operator=(Status&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Status& default_instance() {
    return *internal_default_instance();
  }
  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Status& a, Status& b) {
    a.Swap(&b);
  }
  inline void Swap(Status* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Status* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Status* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Status>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Status& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Status& from) {
    Status::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Status* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "smartivrphonegateway.Status";
  }
  protected:
  explicit Status(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* ptr);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // int32 code = 1;
  void clear_code() ;
  ::int32_t code() const;
  void set_code(::int32_t value);

  private:
  ::int32_t _internal_code() const;
  void _internal_set_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:smartivrphonegateway.Status)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    ::int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_smartivrphonegateway_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SmartIVRRequest

// bool is_playing = 1;
inline void SmartIVRRequest::clear_is_playing() {
  _impl_.is_playing_ = false;
}
inline bool SmartIVRRequest::is_playing() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRRequest.is_playing)
  return _internal_is_playing();
}
inline void SmartIVRRequest::set_is_playing(bool value) {
  _internal_set_is_playing(value);
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRRequest.is_playing)
}
inline bool SmartIVRRequest::_internal_is_playing() const {
  return _impl_.is_playing_;
}
inline void SmartIVRRequest::_internal_set_is_playing(bool value) {
  ;
  _impl_.is_playing_ = value;
}

// string key_press = 2;
inline void SmartIVRRequest::clear_key_press() {
  _impl_.key_press_.ClearToEmpty();
}
inline const std::string& SmartIVRRequest::key_press() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRRequest.key_press)
  return _internal_key_press();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SmartIVRRequest::set_key_press(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.key_press_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRRequest.key_press)
}
inline std::string* SmartIVRRequest::mutable_key_press() {
  std::string* _s = _internal_mutable_key_press();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRRequest.key_press)
  return _s;
}
inline const std::string& SmartIVRRequest::_internal_key_press() const {
  return _impl_.key_press_.Get();
}
inline void SmartIVRRequest::_internal_set_key_press(const std::string& value) {
  ;


  _impl_.key_press_.Set(value, GetArenaForAllocation());
}
inline std::string* SmartIVRRequest::_internal_mutable_key_press() {
  ;
  return _impl_.key_press_.Mutable( GetArenaForAllocation());
}
inline std::string* SmartIVRRequest::release_key_press() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRRequest.key_press)
  return _impl_.key_press_.Release();
}
inline void SmartIVRRequest::set_allocated_key_press(std::string* value) {
  _impl_.key_press_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.key_press_.IsDefault()) {
          _impl_.key_press_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRRequest.key_press)
}

// .smartivrphonegateway.Config config = 3;
inline bool SmartIVRRequest::_internal_has_config() const {
  return this != internal_default_instance() && _impl_.config_ != nullptr;
}
inline bool SmartIVRRequest::has_config() const {
  return _internal_has_config();
}
inline void SmartIVRRequest::clear_config() {
  if (GetArenaForAllocation() == nullptr && _impl_.config_ != nullptr) {
    delete _impl_.config_;
  }
  _impl_.config_ = nullptr;
}
inline const ::smartivrphonegateway::Config& SmartIVRRequest::_internal_config() const {
  const ::smartivrphonegateway::Config* p = _impl_.config_;
  return p != nullptr ? *p : reinterpret_cast<const ::smartivrphonegateway::Config&>(
      ::smartivrphonegateway::_Config_default_instance_);
}
inline const ::smartivrphonegateway::Config& SmartIVRRequest::config() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRRequest.config)
  return _internal_config();
}
inline void SmartIVRRequest::unsafe_arena_set_allocated_config(
    ::smartivrphonegateway::Config* config) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.config_);
  }
  _impl_.config_ = config;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:smartivrphonegateway.SmartIVRRequest.config)
}
inline ::smartivrphonegateway::Config* SmartIVRRequest::release_config() {
  
  ::smartivrphonegateway::Config* temp = _impl_.config_;
  _impl_.config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::smartivrphonegateway::Config* SmartIVRRequest::unsafe_arena_release_config() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRRequest.config)
  
  ::smartivrphonegateway::Config* temp = _impl_.config_;
  _impl_.config_ = nullptr;
  return temp;
}
inline ::smartivrphonegateway::Config* SmartIVRRequest::_internal_mutable_config() {
  
  if (_impl_.config_ == nullptr) {
    auto* p = CreateMaybeMessage<::smartivrphonegateway::Config>(GetArenaForAllocation());
    _impl_.config_ = p;
  }
  return _impl_.config_;
}
inline ::smartivrphonegateway::Config* SmartIVRRequest::mutable_config() {
  ::smartivrphonegateway::Config* _msg = _internal_mutable_config();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRRequest.config)
  return _msg;
}
inline void SmartIVRRequest::set_allocated_config(::smartivrphonegateway::Config* config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.config_;
  }
  if (config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(config);
    if (message_arena != submessage_arena) {
      config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }

  } else {

  }
  _impl_.config_ = config;
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRRequest.config)
}

// bytes audio_content = 4;
inline void SmartIVRRequest::clear_audio_content() {
  _impl_.audio_content_.ClearToEmpty();
}
inline const std::string& SmartIVRRequest::audio_content() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRRequest.audio_content)
  return _internal_audio_content();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SmartIVRRequest::set_audio_content(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.audio_content_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRRequest.audio_content)
}
inline std::string* SmartIVRRequest::mutable_audio_content() {
  std::string* _s = _internal_mutable_audio_content();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRRequest.audio_content)
  return _s;
}
inline const std::string& SmartIVRRequest::_internal_audio_content() const {
  return _impl_.audio_content_.Get();
}
inline void SmartIVRRequest::_internal_set_audio_content(const std::string& value) {
  ;


  _impl_.audio_content_.Set(value, GetArenaForAllocation());
}
inline std::string* SmartIVRRequest::_internal_mutable_audio_content() {
  ;
  return _impl_.audio_content_.Mutable( GetArenaForAllocation());
}
inline std::string* SmartIVRRequest::release_audio_content() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRRequest.audio_content)
  return _impl_.audio_content_.Release();
}
inline void SmartIVRRequest::set_allocated_audio_content(std::string* value) {
  _impl_.audio_content_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.audio_content_.IsDefault()) {
          _impl_.audio_content_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRRequest.audio_content)
}

// -------------------------------------------------------------------

// SmartIVRResponse

// .smartivrphonegateway.SmartIVRResponseType type = 1;
inline void SmartIVRResponse::clear_type() {
  _impl_.type_ = 0;
}
inline ::smartivrphonegateway::SmartIVRResponseType SmartIVRResponse::type() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRResponse.type)
  return _internal_type();
}
inline void SmartIVRResponse::set_type(::smartivrphonegateway::SmartIVRResponseType value) {
   _internal_set_type(value);
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRResponse.type)
}
inline ::smartivrphonegateway::SmartIVRResponseType SmartIVRResponse::_internal_type() const {
  return static_cast<::smartivrphonegateway::SmartIVRResponseType>(_impl_.type_);
}
inline void SmartIVRResponse::_internal_set_type(::smartivrphonegateway::SmartIVRResponseType value) {
  ;
  _impl_.type_ = value;
}

// string text_asr = 2;
inline void SmartIVRResponse::clear_text_asr() {
  _impl_.text_asr_.ClearToEmpty();
}
inline const std::string& SmartIVRResponse::text_asr() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRResponse.text_asr)
  return _internal_text_asr();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SmartIVRResponse::set_text_asr(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.text_asr_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRResponse.text_asr)
}
inline std::string* SmartIVRResponse::mutable_text_asr() {
  std::string* _s = _internal_mutable_text_asr();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRResponse.text_asr)
  return _s;
}
inline const std::string& SmartIVRResponse::_internal_text_asr() const {
  return _impl_.text_asr_.Get();
}
inline void SmartIVRResponse::_internal_set_text_asr(const std::string& value) {
  ;


  _impl_.text_asr_.Set(value, GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::_internal_mutable_text_asr() {
  ;
  return _impl_.text_asr_.Mutable( GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::release_text_asr() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRResponse.text_asr)
  return _impl_.text_asr_.Release();
}
inline void SmartIVRResponse::set_allocated_text_asr(std::string* value) {
  _impl_.text_asr_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.text_asr_.IsDefault()) {
          _impl_.text_asr_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRResponse.text_asr)
}

// string text_bot = 3;
inline void SmartIVRResponse::clear_text_bot() {
  _impl_.text_bot_.ClearToEmpty();
}
inline const std::string& SmartIVRResponse::text_bot() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRResponse.text_bot)
  return _internal_text_bot();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SmartIVRResponse::set_text_bot(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.text_bot_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRResponse.text_bot)
}
inline std::string* SmartIVRResponse::mutable_text_bot() {
  std::string* _s = _internal_mutable_text_bot();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRResponse.text_bot)
  return _s;
}
inline const std::string& SmartIVRResponse::_internal_text_bot() const {
  return _impl_.text_bot_.Get();
}
inline void SmartIVRResponse::_internal_set_text_bot(const std::string& value) {
  ;


  _impl_.text_bot_.Set(value, GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::_internal_mutable_text_bot() {
  ;
  return _impl_.text_bot_.Mutable( GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::release_text_bot() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRResponse.text_bot)
  return _impl_.text_bot_.Release();
}
inline void SmartIVRResponse::set_allocated_text_bot(std::string* value) {
  _impl_.text_bot_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.text_bot_.IsDefault()) {
          _impl_.text_bot_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRResponse.text_bot)
}

// string forward_sip_json = 4;
inline void SmartIVRResponse::clear_forward_sip_json() {
  _impl_.forward_sip_json_.ClearToEmpty();
}
inline const std::string& SmartIVRResponse::forward_sip_json() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRResponse.forward_sip_json)
  return _internal_forward_sip_json();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SmartIVRResponse::set_forward_sip_json(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.forward_sip_json_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRResponse.forward_sip_json)
}
inline std::string* SmartIVRResponse::mutable_forward_sip_json() {
  std::string* _s = _internal_mutable_forward_sip_json();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRResponse.forward_sip_json)
  return _s;
}
inline const std::string& SmartIVRResponse::_internal_forward_sip_json() const {
  return _impl_.forward_sip_json_.Get();
}
inline void SmartIVRResponse::_internal_set_forward_sip_json(const std::string& value) {
  ;


  _impl_.forward_sip_json_.Set(value, GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::_internal_mutable_forward_sip_json() {
  ;
  return _impl_.forward_sip_json_.Mutable( GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::release_forward_sip_json() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRResponse.forward_sip_json)
  return _impl_.forward_sip_json_.Release();
}
inline void SmartIVRResponse::set_allocated_forward_sip_json(std::string* value) {
  _impl_.forward_sip_json_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.forward_sip_json_.IsDefault()) {
          _impl_.forward_sip_json_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRResponse.forward_sip_json)
}

// .smartivrphonegateway.Status status = 5;
inline bool SmartIVRResponse::_internal_has_status() const {
  return this != internal_default_instance() && _impl_.status_ != nullptr;
}
inline bool SmartIVRResponse::has_status() const {
  return _internal_has_status();
}
inline void SmartIVRResponse::clear_status() {
  if (GetArenaForAllocation() == nullptr && _impl_.status_ != nullptr) {
    delete _impl_.status_;
  }
  _impl_.status_ = nullptr;
}
inline const ::smartivrphonegateway::Status& SmartIVRResponse::_internal_status() const {
  const ::smartivrphonegateway::Status* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::smartivrphonegateway::Status&>(
      ::smartivrphonegateway::_Status_default_instance_);
}
inline const ::smartivrphonegateway::Status& SmartIVRResponse::status() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRResponse.status)
  return _internal_status();
}
inline void SmartIVRResponse::unsafe_arena_set_allocated_status(
    ::smartivrphonegateway::Status* status) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = status;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:smartivrphonegateway.SmartIVRResponse.status)
}
inline ::smartivrphonegateway::Status* SmartIVRResponse::release_status() {
  
  ::smartivrphonegateway::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::smartivrphonegateway::Status* SmartIVRResponse::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRResponse.status)
  
  ::smartivrphonegateway::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::smartivrphonegateway::Status* SmartIVRResponse::_internal_mutable_status() {
  
  if (_impl_.status_ == nullptr) {
    auto* p = CreateMaybeMessage<::smartivrphonegateway::Status>(GetArenaForAllocation());
    _impl_.status_ = p;
  }
  return _impl_.status_;
}
inline ::smartivrphonegateway::Status* SmartIVRResponse::mutable_status() {
  ::smartivrphonegateway::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRResponse.status)
  return _msg;
}
inline void SmartIVRResponse::set_allocated_status(::smartivrphonegateway::Status* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.status_;
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(status);
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }

  } else {

  }
  _impl_.status_ = status;
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRResponse.status)
}

// bytes audio_content = 6;
inline void SmartIVRResponse::clear_audio_content() {
  _impl_.audio_content_.ClearToEmpty();
}
inline const std::string& SmartIVRResponse::audio_content() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.SmartIVRResponse.audio_content)
  return _internal_audio_content();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SmartIVRResponse::set_audio_content(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.audio_content_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.SmartIVRResponse.audio_content)
}
inline std::string* SmartIVRResponse::mutable_audio_content() {
  std::string* _s = _internal_mutable_audio_content();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.SmartIVRResponse.audio_content)
  return _s;
}
inline const std::string& SmartIVRResponse::_internal_audio_content() const {
  return _impl_.audio_content_.Get();
}
inline void SmartIVRResponse::_internal_set_audio_content(const std::string& value) {
  ;


  _impl_.audio_content_.Set(value, GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::_internal_mutable_audio_content() {
  ;
  return _impl_.audio_content_.Mutable( GetArenaForAllocation());
}
inline std::string* SmartIVRResponse::release_audio_content() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.SmartIVRResponse.audio_content)
  return _impl_.audio_content_.Release();
}
inline void SmartIVRResponse::set_allocated_audio_content(std::string* value) {
  _impl_.audio_content_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.audio_content_.IsDefault()) {
          _impl_.audio_content_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.SmartIVRResponse.audio_content)
}

// -------------------------------------------------------------------

// Config

// string conversation_id = 1;
inline void Config::clear_conversation_id() {
  _impl_.conversation_id_.ClearToEmpty();
}
inline const std::string& Config::conversation_id() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.Config.conversation_id)
  return _internal_conversation_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Config::set_conversation_id(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.conversation_id_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.Config.conversation_id)
}
inline std::string* Config::mutable_conversation_id() {
  std::string* _s = _internal_mutable_conversation_id();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.Config.conversation_id)
  return _s;
}
inline const std::string& Config::_internal_conversation_id() const {
  return _impl_.conversation_id_.Get();
}
inline void Config::_internal_set_conversation_id(const std::string& value) {
  ;


  _impl_.conversation_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Config::_internal_mutable_conversation_id() {
  ;
  return _impl_.conversation_id_.Mutable( GetArenaForAllocation());
}
inline std::string* Config::release_conversation_id() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.Config.conversation_id)
  return _impl_.conversation_id_.Release();
}
inline void Config::set_allocated_conversation_id(std::string* value) {
  _impl_.conversation_id_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.conversation_id_.IsDefault()) {
          _impl_.conversation_id_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.Config.conversation_id)
}

// -------------------------------------------------------------------

// Status

// int32 code = 1;
inline void Status::clear_code() {
  _impl_.code_ = 0;
}
inline ::int32_t Status::code() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.Status.code)
  return _internal_code();
}
inline void Status::set_code(::int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:smartivrphonegateway.Status.code)
}
inline ::int32_t Status::_internal_code() const {
  return _impl_.code_;
}
inline void Status::_internal_set_code(::int32_t value) {
  ;
  _impl_.code_ = value;
}

// string message = 2;
inline void Status::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& Status::message() const {
  // @@protoc_insertion_point(field_get:smartivrphonegateway.Status.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Status::set_message(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:smartivrphonegateway.Status.message)
}
inline std::string* Status::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:smartivrphonegateway.Status.message)
  return _s;
}
inline const std::string& Status::_internal_message() const {
  return _impl_.message_.Get();
}
inline void Status::_internal_set_message(const std::string& value) {
  ;


  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* Status::_internal_mutable_message() {
  ;
  return _impl_.message_.Mutable( GetArenaForAllocation());
}
inline std::string* Status::release_message() {
  // @@protoc_insertion_point(field_release:smartivrphonegateway.Status.message)
  return _impl_.message_.Release();
}
inline void Status::set_allocated_message(std::string* value) {
  _impl_.message_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.message_.IsDefault()) {
          _impl_.message_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:smartivrphonegateway.Status.message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace smartivrphonegateway


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::smartivrphonegateway::SmartIVRResponseType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::smartivrphonegateway::SmartIVRResponseType>() {
  return ::smartivrphonegateway::SmartIVRResponseType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_smartivrphonegateway_2eproto_2epb_2eh
